"""
Bootstrap the initial monthly partitions for PriceHistory.

`0001_initial` (auto-generated by `makemigrations`) creates the *partitioned
parent* table because ``PriceHistory`` subclasses ``PostgresPartitionedModel``
with ``PartitioningMeta.method = RANGE`` on ``captured_at``. A partitioned parent
holds no rows itself, so we must create at least the current + next month's
partitions before the first write. Thereafter ``manage.py pgpartition`` (driven
by catalog/partitioning.py, scheduled via Beat) keeps the window rolling and the
``prune_price_history`` command drops out-of-window partitions.

This migration is idempotent-ish for bootstrap; ongoing partitions are managed by
pgpartition, not by new migrations.
"""

from datetime import date

from django.db import migrations
from psqlextra.backend.migrations.operations import PostgresAddRangePartition


def _month_partitions():
    """Create recent/current monthly partitions for a local bootstrap.

    Bounds are [from, to), so a month partition is FROM the 1st TO next month 1st.
    ``pgpartition`` takes over after this initial window.
    """
    today = date.today().replace(day=1)
    start_month = _add_months(today, -3)
    windows = []
    for i in range(6):
        lo = _add_months(start_month, i)
        hi = _add_months(lo, 1)
        windows.append((lo.strftime("%Y_%m"), lo.isoformat(), hi.isoformat()))
    return [
        PostgresAddRangePartition(
            model_name="PriceHistory",
            name=name,
            from_values=lo,
            to_values=hi,
        )
        for name, lo, hi in windows
    ]


def _add_months(value, months):
    month = value.month - 1 + months
    year = value.year + month // 12
    month = month % 12 + 1
    return date(year, month, 1)


class Migration(migrations.Migration):
    dependencies = [("catalog", "0001_initial")]
    operations = _month_partitions()
